/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'affiliateUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getAllFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllTodaysDeals' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getFeaturedProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getTodaysDeal' : IDL.Func([IDL.Text], [Product], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'affiliateUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    'getAllFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllTodaysDeals' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getFeaturedProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getTodaysDeal' : IDL.Func([IDL.Text], [Product], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };